INSERT INTO users (
  first_name,
  email,
  username,
  password
) VALUES (
  'Gina',
  'gina@la.gov',
  'demo',
  '$2a$10$tW3KLuaVGGKLxfOjWcBAGu5v/W/HwEQY8ZxhMgqezRyJtTibcgDBW'
);

INSERT INTO users (
  first_name,
  email
) VALUES (
  'Ronson',
  'ronson@la.gov'
);

    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Laurel',
      'W',
      'Kris',
      ARRAY['Laure'],
      'new case',
      DATE('08-15-2012'),
      '9301940744',
      'Joesph_Ledner79@yahoo.com',
      '568 West Crest',
      '7',
      'indian',
      'brown',
      'female',
      'work',
      '1-1000000',
      'single',
      'rent',
      false,
      'not veteran',
      true,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Cornell',
      'W',
      'Sanford',
      ARRAY['Corne'],
      'new case',
      DATE('05-27-1965'),
      '4439540337',
      'Polly_Larkin71@yahoo.com',
      '7534 Cheyenne Knoll',
      '54',
      'chinese',
      'yellow',
      'female',
      'work',
      '1-1000000',
      'single',
      'rent',
      false,
      'not veteran',
      true,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Stephanie',
      'W',
      'Murphy',
      ARRAY['Steph'],
      'new case',
      DATE('02-12-2011'),
      '6659011463',
      'Kirsten_Doyle@hotmail.com',
      '767 Fritsch Stravenue',
      '8',
      'indonesian',
      'yellow',
      'male',
      'work',
      '1-1000000',
      'single',
      'rent',
      false,
      'not veteran',
      false,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Judy',
      'W',
      'Brakus',
      ARRAY['Judy'],
      'new case',
      DATE('05-15-1928'),
      '3833486042',
      'Harrison_Doyle@hotmail.com',
      '03336 Kendall Extensions',
      '91',
      'indian',
      'brown',
      'female',
      'work',
      '1-1000000',
      'single',
      'rent',
      true,
      'not veteran',
      true,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Nichole',
      'W',
      'Ward',
      ARRAY['Nicho'],
      'new case',
      DATE('05-11-1929'),
      '0772038999',
      'Griffin.Gleichner45@hotmail.com',
      '537 Gulgowski Green',
      '90',
      'mexican',
      'brown',
      'female',
      'work',
      '1-1000000',
      'single',
      'rent',
      false,
      'not veteran',
      false,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Giuseppe',
      'W',
      'Becker',
      ARRAY['Giuse'],
      'new case',
      DATE('03-05-1987'),
      '4096355662',
      'Dayton46@hotmail.com',
      '2790 Jacobson Bridge',
      '32',
      'mexican',
      'brown',
      'male',
      'work',
      '1-1000000',
      'single',
      'rent',
      true,
      'not veteran',
      false,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Adele',
      'W',
      'Moore',
      ARRAY['Adele'],
      'new case',
      DATE('11-24-1977'),
      '6242506796',
      'Bertha.Morar52@gmail.com',
      '205 Helene Mission',
      '42',
      'indonesian',
      'yellow',
      'male',
      'work',
      '1-1000000',
      'single',
      'rent',
      false,
      'not veteran',
      true,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Destany',
      'W',
      'Rodriguez',
      ARRAY['Desta'],
      'new case',
      DATE('01-11-1921'),
      '3735711675',
      'Marty81@hotmail.com',
      '9051 Reichert Place',
      '98',
      'indonesian',
      'yellow',
      'female',
      'work',
      '1-1000000',
      'single',
      'rent',
      true,
      'not veteran',
      true,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Elsa',
      'W',
      'Muller',
      ARRAY['Elsa'],
      'new case',
      DATE('02-20-1927'),
      '0793763961',
      'Cortez.Blick@gmail.com',
      '268 Alexandrine Gardens',
      '92',
      'indian',
      'brown',
      'female',
      'work',
      '1-1000000',
      'single',
      'rent',
      true,
      'not veteran',
      false,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Juvenal',
      'W',
      'Shields',
      ARRAY['Juven'],
      'new case',
      DATE('05-19-1977'),
      '3480066689',
      'Gracie6@yahoo.com',
      '61905 Demarco Turnpike',
      '42',
      'chinese',
      'yellow',
      'male',
      'work',
      '1-1000000',
      'single',
      'rent',
      false,
      'not veteran',
      false,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Lola',
      'W',
      'Hills',
      ARRAY['Lola'],
      'new case',
      DATE('11-07-1942'),
      '9473732128',
      'Warren.Strosin93@hotmail.com',
      '985 Matilda Junctions',
      '77',
      'chinese',
      'yellow',
      'female',
      'work',
      '1-1000000',
      'single',
      'rent',
      true,
      'not veteran',
      true,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Cleta',
      'W',
      'Hodkiewicz',
      ARRAY['Cleta'],
      'new case',
      DATE('07-10-1967'),
      '7614895023',
      'Eriberto_Beatty85@hotmail.com',
      '5973 Aniyah Glen',
      '52',
      'indonesian',
      'yellow',
      'male',
      'work',
      '1-1000000',
      'single',
      'rent',
      true,
      'not veteran',
      false,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Pinkie',
      'W',
      'Rowe',
      ARRAY['Pinki'],
      'new case',
      DATE('02-08-2002'),
      '3323823272',
      'Delfina.Jacobs@gmail.com',
      '832 Erdman Crossroad',
      '17',
      'indonesian',
      'yellow',
      'male',
      'work',
      '1-1000000',
      'single',
      'rent',
      true,
      'not veteran',
      false,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Kathryne',
      'W',
      'Waters',
      ARRAY['Kathr'],
      'new case',
      DATE('03-20-1959'),
      '2277115648',
      'Brendan_Nader@gmail.com',
      '7767 Krajcik Burgs',
      '60',
      'indonesian',
      'yellow',
      'female',
      'work',
      '1-1000000',
      'single',
      'rent',
      false,
      'not veteran',
      false,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Warren',
      'W',
      'Dickens',
      ARRAY['Warre'],
      'new case',
      DATE('05-31-1964'),
      '2594855462',
      'Rafaela.Breitenberg@gmail.com',
      '5222 Haylie Freeway',
      '55',
      'indonesian',
      'yellow',
      'female',
      'work',
      '1-1000000',
      'single',
      'rent',
      true,
      'not veteran',
      false,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Reynold',
      'W',
      'Schmeler',
      ARRAY['Reyno'],
      'new case',
      DATE('02-18-1999'),
      '0482798190',
      'Mckayla80@yahoo.com',
      '11381 Danial Mill',
      '20',
      'chinese',
      'yellow',
      'male',
      'work',
      '1-1000000',
      'single',
      'rent',
      false,
      'not veteran',
      false,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Michale',
      'W',
      'Carter',
      ARRAY['Micha'],
      'new case',
      DATE('12-22-1933'),
      '9504579590',
      'Winfield54@hotmail.com',
      '0557 Lonie Light',
      '86',
      'caucasian',
      'white',
      'female',
      'work',
      '1-1000000',
      'single',
      'rent',
      false,
      'not veteran',
      true,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Lee',
      'W',
      'Crooks',
      ARRAY['Lee'],
      'new case',
      DATE('11-22-2001'),
      '0335719112',
      'Kianna.Rau@yahoo.com',
      '7629 Ebert Harbor',
      '18',
      'chinese',
      'yellow',
      'female',
      'work',
      '1-1000000',
      'single',
      'rent',
      true,
      'not veteran',
      false,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Daisha',
      'W',
      'Lesch',
      ARRAY['Daish'],
      'new case',
      DATE('05-05-1965'),
      '3045259493',
      'Anya95@gmail.com',
      '8824 Durward Mountains',
      '54',
      'chinese',
      'yellow',
      'female',
      'work',
      '1-1000000',
      'single',
      'rent',
      true,
      'not veteran',
      true,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Raul',
      'W',
      'Parisian',
      ARRAY['Raul'],
      'new case',
      DATE('02-16-1952'),
      '8818577394',
      'Mafalda.Douglas@gmail.com',
      '14037 Cummerata Harbor',
      '67',
      'indian',
      'brown',
      'female',
      'work',
      '1-1000000',
      'single',
      'rent',
      true,
      'not veteran',
      true,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Harvey',
      'W',
      'Hettinger',
      ARRAY['Harve'],
      'new case',
      DATE('01-13-1978'),
      '6657333392',
      'Wilfredo_Schimmel81@hotmail.com',
      '57671 Treutel Coves',
      '41',
      'chinese',
      'yellow',
      'male',
      'work',
      '1-1000000',
      'single',
      'rent',
      true,
      'not veteran',
      false,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Angelina',
      'W',
      'Hagenes',
      ARRAY['Angel'],
      'new case',
      DATE('06-02-1927'),
      '2858935130',
      'Wilhelm_Champlin42@hotmail.com',
      '26712 Francisca Common',
      '92',
      'indian',
      'brown',
      'female',
      'work',
      '1-1000000',
      'single',
      'rent',
      true,
      'not veteran',
      false,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Alexanne',
      'W',
      'Vandervort',
      ARRAY['Alexa'],
      'new case',
      DATE('11-09-2001'),
      '1960204289',
      'Malinda.Smith76@hotmail.com',
      '877 Jerald Cove',
      '18',
      'chinese',
      'yellow',
      'female',
      'work',
      '1-1000000',
      'single',
      'rent',
      false,
      'not veteran',
      true,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Aylin',
      'W',
      'Gottlieb',
      ARRAY['Aylin'],
      'new case',
      DATE('02-22-1925'),
      '3768503984',
      'Adolfo.Larson@gmail.com',
      '5715 Jermey Plaza',
      '94',
      'indian',
      'brown',
      'female',
      'work',
      '1-1000000',
      'single',
      'rent',
      false,
      'not veteran',
      true,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Cristal',
      'W',
      'Kuhn',
      ARRAY['Crist'],
      'new case',
      DATE('08-21-1932'),
      '4994040519',
      'Matteo_Zboncak40@gmail.com',
      '34842 Gerlach Cliff',
      '87',
      'indonesian',
      'yellow',
      'male',
      'work',
      '1-1000000',
      'single',
      'rent',
      true,
      'not veteran',
      true,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Zita',
      'W',
      'Trantow',
      ARRAY['Zita'],
      'new case',
      DATE('03-23-1990'),
      '8108165839',
      'Noe.Towne38@yahoo.com',
      '47641 VonRueden Forest',
      '29',
      'mexican',
      'brown',
      'male',
      'work',
      '1-1000000',
      'single',
      'rent',
      true,
      'not veteran',
      true,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Rosetta',
      'W',
      'Balistreri',
      ARRAY['Roset'],
      'new case',
      DATE('08-30-1934'),
      '4397618949',
      'Norwood54@yahoo.com',
      '4908 Bonnie Centers',
      '85',
      'chinese',
      'yellow',
      'male',
      'work',
      '1-1000000',
      'single',
      'rent',
      true,
      'not veteran',
      false,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Phyllis',
      'W',
      'Zboncak',
      ARRAY['Phyll'],
      'new case',
      DATE('02-22-1996'),
      '9433625702',
      'Jeanette.Skiles15@yahoo.com',
      '5759 Herman Spring',
      '23',
      'caucasian',
      'white',
      'female',
      'work',
      '1-1000000',
      'single',
      'rent',
      true,
      'not veteran',
      false,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-322',
      'CC 1235',
      ARRAY['VN 1235'],
      'warrant',
      1
    );
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-323',
      'CC 1236',
      ARRAY['VN 1236'],
      'warrant',
      2
    );
    
    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Russell',
      'W',
      'Kuvalis',
      ARRAY['Russe'],
      'new case',
      DATE('08-15-1928'),
      '8729273774',
      'Kennith_Powlowski@gmail.com',
      '21406 Art Wall',
      '91',
      'caucasian',
      'white',
      'female',
      'work',
      '1-1000000',
      'single',
      'rent',
      false,
      'not veteran',
      false,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-326',
      'CC 1239',
      ARRAY['VN 1239'],
      'warrant',
      5
    );
    
    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Camilla',
      'W',
      'Turcotte',
      ARRAY['Camil'],
      'new case',
      DATE('01-12-1966'),
      '9805139872',
      'Afton63@hotmail.com',
      '9971 Alayna Bridge',
      '53',
      'indian',
      'brown',
      'male',
      'work',
      '1-1000000',
      'single',
      'rent',
      false,
      'not veteran',
      true,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-324',
      'CC 1237',
      ARRAY['VN 1237'],
      'warrant',
      3
    );
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-327',
      'CC 1240',
      ARRAY['VN 1240'],
      'warrant',
      6
    );
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-329',
      'CC 1242',
      ARRAY['VN 1242'],
      'warrant',
      8
    );
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-330',
      'CC 1243',
      ARRAY['VN 1243'],
      'warrant',
      9
    );
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-325',
      'CC 1238',
      ARRAY['VN 1238'],
      'warrant',
      4
    );
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-332',
      'CC 1245',
      ARRAY['VN 1245'],
      'warrant',
      11
    );
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-328',
      'CC 1241',
      ARRAY['VN 1241'],
      'warrant',
      7
    );
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-331',
      'CC 1244',
      ARRAY['VN 1244'],
      'warrant',
      10
    );
    
    INSERT INTO participants (
      first_name,
      middle_name,
      last_name,
      aka,
      status,
      dob,
      phone,
      email,
      address,
      age,
      ethnicity,
      race,
      gender,
      income_source,
      income_range,
      family_status,
      housing_status,
      chronic_homeless,
      veteran_status,
      urgent,
      services,
      notes,
      background_check)
    VALUES (
      'Isobel',
      'W',
      'Weimann',
      ARRAY['Isobe'],
      'new case',
      DATE('08-20-1954'),
      '8822904498',
      'Renee.Lesch45@yahoo.com',
      '1497 Tiana Spur',
      '65',
      'indonesian',
      'yellow',
      'female',
      'work',
      '1-1000000',
      'single',
      'rent',
      true,
      'not veteran',
      true,
      ARRAY['service1', 'service2'],
      '',
      ARRAY['']);
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-336',
      'CC 1249',
      ARRAY['VN 1249'],
      'warrant',
      15
    );
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-337',
      'CC 1250',
      ARRAY['VN 1250'],
      'warrant',
      16
    );
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-338',
      'CC 1251',
      ARRAY['VN 1251'],
      'warrant',
      17
    );
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-335',
      'CC 1248',
      ARRAY['VN 1248'],
      'warrant',
      14
    );
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-334',
      'CC 1247',
      ARRAY['VN 1247'],
      'warrant',
      13
    );
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-341',
      'CC 1254',
      ARRAY['VN 1254'],
      'warrant',
      20
    );
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-342',
      'CC 1255',
      ARRAY['VN 1255'],
      'warrant',
      21
    );
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-344',
      'CC 1257',
      ARRAY['VN 1257'],
      'warrant',
      23
    );
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-343',
      'CC 1256',
      ARRAY['VN 1256'],
      'warrant',
      22
    );
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-345',
      'CC 1258',
      ARRAY['VN 1258'],
      'warrant',
      24
    );
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-340',
      'CC 1253',
      ARRAY['VN 1253'],
      'warrant',
      19
    );
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-348',
      'CC 1261',
      ARRAY['VN 1261'],
      'warrant',
      27
    );
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-347',
      'CC 1260',
      ARRAY['VN 1260'],
      'warrant',
      26
    );
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-351',
      'CC 1264',
      ARRAY['VN 1264'],
      'warrant',
      30
    );
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-339',
      'CC 1252',
      ARRAY['VN 1252'],
      'warrant',
      18
    );
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-349',
      'CC 1262',
      ARRAY['VN 1262'],
      'warrant',
      28
    );
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-333',
      'CC 1246',
      ARRAY['VN 1246'],
      'warrant',
      12
    );
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-352',
      'CC 1265',
      ARRAY['VN 1265'],
      'warrant',
      31
    );
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-350',
      'CC 1263',
      ARRAY['VN 1263'],
      'warrant',
      29
    );
    
    INSERT INTO citations (
      citation_number,
      court_code,
      violations,
      citation_status,
      participant_id
    ) VALUES (
      '1123-346',
      'CC 1259',
      ARRAY['VN 1259'],
      'warrant',
      25
    );
    