export { ClinicFormGroup } from './ClinicFormGroup'
export { ContactInfoFormGroup } from './ContactInfoFormGroup'
export { GeneralInfoFormGroup } from './GeneralInfoFormGroup'
export { FamilyAndIncomeFormGroup } from './FamilyAndIncomeFormGroup'
export { AgreementsFormGroup } from './AgreementsFormGroup'
export { ObligationsFormGroup } from './ObligationsFormGroup'
